/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import LocationAndMeteo.Localita;
import LocationAndMeteo.Meteo;
import RichiestaGeoLocalizzazione.Richiesta;
import RichiestaMeteo.Estrattore1;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;

/**
 *
 * @author Alberto
 */
public class Grafica extends javax.swing.JFrame {

    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
        this.setSize(400, 400);
        this.setVisible(true);
        this.setResizable(false);
        this.setTitle("Meteo di Andrea Milesi");
        f_tempo.setEditable(false);
        f_temperatura.setEditable(false);
        f_umidita.setEditable(false);
        f_pressione.setEditable(false);
        sfondo.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        f_indirizzo = new javax.swing.JTextField();
        f_tempo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        f_temperatura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        f_umidita = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        f_pressione = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        errore = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 51));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 51));
        jButton1.setText("Cerca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(54, 154, 82, 25);

        f_indirizzo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(f_indirizzo);
        f_indirizzo.setBounds(31, 106, 142, 42);

        f_tempo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(f_tempo);
        f_tempo.setBounds(223, 106, 142, 42);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("Indirizzo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(31, 86, 142, 17);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setText("Tempo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(223, 86, 142, 17);

        f_temperatura.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(f_temperatura);
        f_temperatura.setBounds(223, 174, 142, 42);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setText("Temperatura");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(223, 154, 142, 17);

        f_umidita.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(f_umidita);
        f_umidita.setBounds(223, 242, 142, 42);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 51));
        jLabel4.setText("Umidità");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(223, 222, 142, 17);

        f_pressione.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(f_pressione);
        f_pressione.setBounds(223, 310, 142, 42);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 51));
        jLabel5.setText("Pressione");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(223, 290, 142, 17);
        getContentPane().add(errore);
        errore.setBounds(31, 242, 142, 42);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 51));
        jLabel6.setText("Inserisci una località");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(31, 27, 334, 41);

        sfondo.setBackground(new java.awt.Color(204, 0, 102));
        getContentPane().add(sfondo);
        sfondo.setBounds(0, 0, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        errore.setText("");
        Localita location = new Localita (f_indirizzo.getText());
        try {
            Richiesta.get(location);
            location = RichiestaGeoLocalizzazione.Estrattore.EstrattoreLocalizzazione (location);
            RichiestaMeteo.Richiesta1.get(location);
            Meteo w = Estrattore1.EstrattoreTempo(location);
            f_tempo.setText(w.getMeteo());
            f_temperatura.setText(w.getTemperatura());
            f_pressione.setText(w.getPressione());
            f_umidita.setText(w.getUmidita());
        } catch (IOException ex) {
            errore.setText("Località non trovata.");
        
        } catch (ParserConfigurationException ex) {
            errore.setText("Località non trovata.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errore;
    private javax.swing.JTextField f_indirizzo;
    private javax.swing.JTextField f_pressione;
    private javax.swing.JTextField f_temperatura;
    private javax.swing.JTextField f_tempo;
    private javax.swing.JTextField f_umidita;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel sfondo;
    // End of variables declaration//GEN-END:variables
}
